Adding a missing closing tag in brh.xml
Got the following error when trying to parse the file using `lxml`:
```
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: characters line 29 and ldml, line 45, column 8
```
This PR adds a closing tag for the `characters` tag on line 35.